name: Generate Daily Roster

on:
  schedule:
    # Runs automatically every hour at the 5-minute mark
    - cron: '5 * * * *'
  workflow_dispatch:
    # Allows you to manually run the script from the Actions tab

# Set permissions for the entire workflow
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job: Runs the Python script to generate the HTML file
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-docx

      - name: Run the roster script
        env:
          ALADTEC_USERNAME: ${{ secrets.ALADTEC_USERNAME }}
          ALADTEC_PASSWORD: ${{ secrets.ALADTEC_PASSWORD }}
          MEMBER_DATA: ${{ secrets.MEMBER_DATA }}
        run: python get_schedule.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  # Deploy job: Takes the generated file and publishes it to GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

