name: Generate Daily Roster

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-docx

      - name: Run the roster script
        env:
          ALADTEC_USERNAME: ${{ secrets.ALADTEC_USERNAME }}
          ALADTEC_PASSWORD: ${{ secrets.ALADTEC_PASSWORD }}
          MEMBER_DATA: ${{ secrets.MEMBER_DATA }}
        run: python get_schedule.py

      # --- THIS IS THE NEW DIAGNOSTIC STEP ---
      - name: Verify generated files
        run: |
          echo "Listing all files in the workspace..."
          ls -R
          echo "---"
          echo "Listing contents of the 'docs' folder specifically..."
          ls -l docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

